# Site identity (improves feed + SEO)
url: https://leventkaya.com         # <-- set your production domain
baseurl: ""                         # "" for root
lang: en

author:
  name: Levent Kaya

title: Levent Kaya's Website
description: Personal notes on graphics, OS-dev, C/C++ and low-level experiments.
email: leventkayadev@gmail.com
author:
  name: Levent Kaya
  social:
    - { name: GitHub,  url: "https://github.com/lvntky" }
    - { name: LinkedIn, url: "https://www.linkedin.com/in/levent-kaya/" }

theme: low
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

permalink: /posts/:title.html

feed:
  path: rss.xml
  # Optional: limit items or include categories
  # limit: 30

# Make all posts use the post layout
defaults:
  - scope: { path: "", type: "posts" }
    values: { layout: post }

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
